### ISSUE TITLE
Use `terraform import` to manage existing resources in terraform 

### ISSUE THREAD

**Issue by mawasile** [rpothin/PowerPlatform-Governance-With-Terraform#4]
Hi

I've spotted this:
https://github.com/rpothin/PowerPlatform-Governance-With-Terraform/blob/f27510e87219eb7a6986ba18fa44b4cd25079727/notebooks/convert-existing-dlp-policies-to-tfvars-files.dib#L9 

Check out `terraform import` instead: https://developer.hashicorp.com/terraform/cli/import/usage
it is implemented on all resources but wasn't tested

**Comment by rpothin** [comment]
Hi @mawasile,

I am happy to see you keep an eye on this repo.

My goal is to use the `terraform import` command in the next step of the process.

My idea is to try to simplify the on-boarding process of people with an existing footprint in Power Platform:
1. Synchronize existing DLP policies to a JSON file
2. Convert each existing DLP policy to a tfvars file with a predefined format - my approach is one tfvars / state file per DLP policy
3. Run `terraform import` for each DLP policy using a GitHub workflow with inputs
4. Switch to infrastructure as code to manage the DLP policies

But thank you very much for your feedback. I will let you know the results at the end of my tests.

Please, next time use the discussions to share feedbacks like this one. I will convert the discussion into an issue if it makes sense ☺️

Have a great day.
Raphael
